# Generated by Django 5.1.3 on 2024-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_categories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_active_menu',
            field=models.BooleanField(default=True),
        ),
    ]
